{
 "title": "Garmadon - HDFS",
 "tags": [ "git" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "uri",
    "query": "{\"find\": \"terms\", \"field\": \"uri\"}"
   },
   { "name": "path", "query": "/apps,/glup,/tmp,/user,/var" },
   {
    "name": "action",
    "query": "{\"find\": \"terms\", \"field\": \"action\",\"query\":\"uri:$uri AND dst_path:$path\"}"
   }
  ]
 },
 "panels": [
  { "title": "FS OPS Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "FS OPS per action on $uri",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "action",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event_type:FS_EVENT AND uri:$uri",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FS OPS per path on $uri",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "apps",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event_type:FS_EVENT AND uri:$uri AND dst_path:\"/apps\"",
     "timeField": "timestamp"
    },
    {
     "alias": "glup",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event_type:FS_EVENT AND uri:$uri AND dst_path:\"/glup\"",
     "timeField": "timestamp"
    },
    {
     "alias": "user",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event_type:FS_EVENT AND uri:$uri AND dst_path:\"/user\"",
     "timeField": "timestamp"
    },
    {
     "alias": "tmp",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event_type:FS_EVENT AND uri:$uri AND dst_path:\"/tmp\"",
     "timeField": "timestamp"
    },
    {
     "alias": "var",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event_type:FS_EVENT AND uri:$uri AND dst_path:\"/var\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FS OPS Per User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "FS OPS $action per user on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "repeat": "action",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "username",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per user on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "username",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per user on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "username",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per user on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "username",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "FS OPS Per Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "FS OPS $action per application on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "repeat": "action",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "application_id",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per application on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "application_id",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per application on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "application_id",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per application on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "application_id",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "FS OPS Per Framework/Component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "FS OPS $action per application on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "repeat": "action",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{framework}}.{{component}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:489",
         "fake": true,
         "field": "framework",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:240",
         "fake": true,
         "field": "component",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:241",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:238", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per application on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{framework}}.{{component}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:489",
         "fake": true,
         "field": "framework",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:240",
         "fake": true,
         "field": "component",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:241",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:238", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per application on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{framework}}.{{component}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:489",
         "fake": true,
         "field": "framework",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:240",
         "fake": true,
         "field": "component",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:241",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:238", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per application on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{framework}}.{{component}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:489",
         "fake": true,
         "field": "framework",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:240",
         "fake": true,
         "field": "component",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:241",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:238", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per application on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{framework}}.{{component}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:489",
         "fake": true,
         "field": "framework",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:240",
         "fake": true,
         "field": "component",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:241",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:238", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}