{
 "title": "Garmadon - Spark Stages",
 "tags": [ "git" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "username",
    "query": "{\"find\": \"terms\", \"field\": \"username\",\"query\": \"event_type:SPARK_STAGE_EVENT\"}"
   },
   {
    "name": "application_id",
    "query": "{\"find\": \"terms\", \"field\": \"application_id\", \"query\": \"event_type:SPARK_STAGE_EVENT AND username:$username\"}"
   },
   {
    "name": "attempt_id",
    "query": "{\"find\": \"terms\", \"field\": \"attempt_id\", \"query\": \"event_type:SPARK_STAGE_EVENT AND username:$username AND application_id:$application_id\"}"
   },
   {
    "name": "stage_id",
    "query": "{\"find\": \"terms\", \"field\": \"stage_id\", \"query\": \"event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id\"}"
   },
   {
    "name": "stage_attempt_id",
    "query": "{\"find\": \"terms\", \"field\": \"stage_attempt_id\", \"query\": \"event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id\"}"
   },
   {
    "name": "uri",
    "query": "{\"find\": \"terms\", \"field\": \"uri\", \"query\": \"username:$username AND application_id:$application_id AND attempt_id:$attempt_id\"}"
   }
  ]
 },
 "panels": [
  { "title": "OVERVIEW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "%usage",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": {
        "interval": "10s",
        "min_doc_count": 0,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "cpu_%load",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:JVMSTATS_EVENT AND tag:YARN_APPLICATION AND application_id:$application_id AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total Containers Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": {
        "interval": "10s",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:CONTAINER_MONITORING_EVENT AND type:MEMORY AND tag:NODEMANAGER AND application_id:$application_id AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    },
    {
     "alias": "max",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": {
        "interval": "10s",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "limit",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:CONTAINER_MONITORING_EVENT AND type:MEMORY AND tag:NODEMANAGER AND application_id:$application_id AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Number of Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "#tasks",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "num_tasks",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND tag:YARN_APPLICATION AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "HEAP Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "heap_used",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tag:YARN_APPLICATION AND application_id:$application_id AND attempt_id:$attempt_id",
       "timeField": "timestamp"
      },
      {
       "alias": "max",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "heap_max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tag:YARN_APPLICATION AND application_id:$application_id AND attempt_id:$attempt_id",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "OFF-HEAP Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "nonheap_used",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tag:YARN_APPLICATION AND application_id:$application_id AND attempt_id:$attempt_id",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Total GC duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "ParNew",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(ParNew)_time",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tag:YARN_APPLICATION AND application_id:$application_id AND attempt_id:$attempt_id",
       "timeField": "timestamp"
      },
      {
       "alias": "G1 Young Generation",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(G1 Young Generation)_time",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tag:YARN_APPLICATION AND application_id:$application_id AND attempt_id:$attempt_id",
       "timeField": "timestamp"
      },
      {
       "alias": "ConcurrentMarkSweep",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(ConcurrentMarkSweep)_time",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tag:YARN_APPLICATION AND application_id:$application_id AND attempt_id:$attempt_id",
       "timeField": "timestamp"
      },
      {
       "alias": "G1 Old Generation",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(G1 Old Generation)_time",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tag:YARN_APPLICATION AND application_id:$application_id AND attempt_id:$attempt_id",
       "timeField": "timestamp"
      },
      {
       "alias": "PS MarkSweep",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(PS MarkSweep)_time",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tag:YARN_APPLICATION AND application_id:$application_id AND attempt_id:$attempt_id",
       "timeField": "timestamp"
      },
      {
       "alias": "PS Scavenge",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(PS Scavenge)_time",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tag:YARN_APPLICATION AND application_id:$application_id AND attempt_id:$attempt_id",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Total GC Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "ConcurrentMarkSweep",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "1" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(ConcurrentMarkSweep)_count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tag:YARN_APPLICATION AND application_id:$application_id AND attempt_id:$attempt_id",
       "timeField": "timestamp"
      },
      {
       "alias": "G1 Old Generation",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(G1 Old Generation)_count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tag:YARN_APPLICATION AND application_id:$application_id AND attempt_id:$attempt_id",
       "timeField": "timestamp"
      },
      {
       "alias": "G1 Young Generation",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(G1 Young Generation)_time",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tag:YARN_APPLICATION AND application_id:$application_id AND attempt_id:$attempt_id",
       "timeField": "timestamp"
      },
      {
       "alias": "PS MarkSweep",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(PS MarkSweep)_count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tag:YARN_APPLICATION AND application_id:$application_id AND attempt_id:$attempt_id",
       "timeField": "timestamp"
      },
      {
       "alias": "PS Scavenge",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(PS Scavenge)_count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tag:YARN_APPLICATION AND application_id:$application_id AND attempt_id:$attempt_id",
       "timeField": "timestamp"
      },
      {
       "alias": "ParNew",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(ParNew)_count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tag:YARN_APPLICATION AND application_id:$application_id AND attempt_id:$attempt_id",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "DURATION",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 19 },
     "content": "Executor: CPU Time the executors spends actually running all tasks of the stage (including fetching shuffle data).\n\nExecutor deserialize: CPU Time taken on the executors to deserialize all tasks of the stage"
    },
    {
     "title": "CPU Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "executor",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "executor_cpu_time",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id AND stage_attempt_id:$stage_attempt_id",
       "timeField": "timestamp"
      },
      {
       "alias": "executor deserialize",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "executor_deserialize_cpu_time",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id AND stage_attempt_id:$stage_attempt_id",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
     "content": "Executor run time: Time the executors spends actually running all tasks of the stage (including fetching shuffle data)\n\nJvm gc time: Amount of time the JVM spent in garbage collection while executing the stage \n\nExecutor deserialize time: Time taken on the executors to deserialize all tasks of the stage\n\nResult serialization time: Amount of time spent serializing all tasks of the stage result"
    },
    {
     "title": "CPU Time spends actually running the stage (including fetching shuffle data)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "executor run time",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "executor_run_time",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id AND stage_attempt_id:$stage_attempt_id",
       "timeField": "timestamp"
      },
      {
       "alias": "jvm gc time",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "jvm_gc_time",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id AND stage_attempt_id:$stage_attempt_id",
       "timeField": "timestamp"
      },
      {
       "alias": "executor deserialize time",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "executor_deserialize_time",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id AND stage_attempt_id:$stage_attempt_id",
       "timeField": "timestamp"
      },
      {
       "alias": "result serialization time",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "result_serialization_time",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id AND stage_attempt_id:$stage_attempt_id",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "SHUFFLE READ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of records read from the shuffle",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "#shuffle read records",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "shuffle_read_records",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id AND stage_attempt_id:$stage_attempt_id",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Time the task spent waiting for remote shuffle blocks",
     "type": "graph",
     "description": "This only includes the time blocking on shuffle input data. For instance if block B is being fetched while the task is still not finished processing block A, it is not considered to be blocking on block B.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "shuffle fetch wait time",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "shuffle_read_fetch_wait_time",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id AND stage_attempt_id:$stage_attempt_id",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Bytes fetched in the shuffle",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "shuffle read local bytes",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "shuffle_read_local_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id AND stage_attempt_id:$stage_attempt_id",
       "timeField": "timestamp"
      },
      {
       "alias": "shuffle read remote bytes",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "shuffle_read_remote_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id AND stage_attempt_id:$stage_attempt_id",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Number of blocks fetched in this shuffle",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "shuffle read local blocks",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "shuffle_read_local_blocks_fetched",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id AND stage_attempt_id:$stage_attempt_id",
       "timeField": "timestamp"
      },
      {
       "alias": "shuffle read remote blocks",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "shuffle_read_remote_blocks_fetched",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id AND stage_attempt_id:$stage_attempt_id",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "SHUFFLE WRITE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of records written to the shuffle",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "#shuffle write records",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "shuffle_write_shuffle_records",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id AND stage_attempt_id:$stage_attempt_id",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Number of bytes written for the shuffle",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "shuffle write bytes",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "shuffle_write_shuffle_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id AND stage_attempt_id:$stage_attempt_id",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Time spent blocking on writes to disk or buffer cache",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "shuffle write time",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "shuffle_write_shuffle_time",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id AND stage_attempt_id:$stage_attempt_id",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "INPUT/OUTPUT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Records",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "repeat": "uri",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "#input records",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "input_records",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id AND stage_attempt_id:$stage_attempt_id",
       "timeField": "timestamp"
      },
      {
       "alias": "#output records",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "output_records",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id AND stage_attempt_id:$stage_attempt_id",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "input bytes",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "input_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id AND stage_attempt_id:$stage_attempt_id",
       "timeField": "timestamp"
      },
      {
       "alias": "output bytes",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "output_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id AND stage_attempt_id:$stage_attempt_id",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "OTHER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Peak memory used by internal data structures created during shuffles, aggregations and joins",
     "type": "graph",
     "description": "The value of this accumulator should be approximately the sum of the peak sizes across all such data structures created in this task. For SQL jobs, this only tracks all unsafe operators and ExternalSort",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "peak execution memory",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "2",
         "settings": {
          "interval": "auto",
          "min_doc_count": 1,
          "trimEdges": null
         },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "peak_execution_memory",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND tag:YARN_APPLICATION AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "The number of bytes transmitted back to the driver as the TaskResult",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "result size",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "2",
         "settings": {
          "interval": "auto",
          "min_doc_count": 1,
          "trimEdges": null
         },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "result_size",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND tag:YARN_APPLICATION AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Number of in-memory/on-disk bytes spilled",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "in-memory",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "memory_bytes_spilled",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id AND stage_attempt_id:$stage_attempt_id",
       "timeField": "timestamp"
      },
      {
       "alias": "on-disk",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "disk_bytes_spilled",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND attempt_id:$attempt_id AND stage_id:$stage_id AND stage_attempt_id:$stage_attempt_id",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "FS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "FS action on $uri",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "repeat": "uri",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "action",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "2",
         "settings": {
          "interval": "auto",
          "min_doc_count": 0,
          "trimEdges": null
         },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "act",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "event_type:FS_EVENT AND application_id:$application_id AND attempt_id:$attempt_id",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}