{
 "title": "Garmadon - Compute",
 "tags": [ "git" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "{\"find\": \"terms\", \"field\": \"hostname\"}"
   },
   {
    "name": "username",
    "query": "{\"find\": \"terms\", \"field\": \"username\"}"
   },
   {
    "name": "framework",
    "query": "{\"find\": \"terms\", \"field\": \"framework\"}"
   },
   {
    "name": "component",
    "query": "{\"find\": \"terms\", \"field\": \"component\", \"query\":\"framework:$framework\"}"
   }
  ]
 },
 "panels": [
  { "title": "Yarn Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "YARN Memory Used/Reserved",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:CONTAINER_MONITORING_EVENT AND type:MEMORY AND tag:NODEMANAGER AND hostname:$hostname",
     "timeField": "timestamp"
    },
    {
     "alias": "reserved",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "limit",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:CONTAINER_MONITORING_EVENT AND type:MEMORY AND tag:NODEMANAGER AND hostname:$hostname",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Applications/Containers runnning",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "#containers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "container_id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "event_type:CONTAINER_MONITORING_EVENT AND type:MEMORY AND tag:NODEMANAGER AND hostname:$hostname",
     "timeField": "timestamp"
    },
    {
     "alias": "#apps",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "application_id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "event_type:CONTAINER_MONITORING_EVENT AND type:MEMORY AND tag:NODEMANAGER AND hostname:$hostname",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Disks bytes reads/writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "reads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "writebytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": " event_type:OS AND tag:FORWARDER AND hostname:$hostname",
     "timeField": "timestamp"
    },
    {
     "alias": "writes",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "readbytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:OS AND tag:FORWARDER AND hostname:$hostname",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Network tx/rx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "rx",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rx",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:OS AND tag:FORWARDER AND hostname:$hostname",
     "timeField": "timestamp"
    },
    {
     "alias": "tx",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tx",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:OS AND tag:FORWARDER AND hostname:$hostname",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top App Consumer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top app running container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "application_id",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "container_id",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "query": "event_type:CONTAINER_MONITORING_EVENT AND type:MEMORY AND tag:NODEMANAGER",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Top app reserved memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "{{application_id}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "application_id",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "limit",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:CONTAINER_MONITORING_EVENT AND type:MEMORY AND tag:NODEMANAGER",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "#Applications Per User",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "username",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "application_id",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tag:YARN_APPLICATION AND hostname:$hostname AND username:$username",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "#Containers Per User",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "username",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "container_id",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tag:YARN_APPLICATION AND hostname:$hostname AND username:$username",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Framework/Component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "#Applications Per Framework",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "framework",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "application_id",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tag:YARN_APPLICATION AND hostname:$hostname AND framework:$framework AND component:$component",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "#Container Per Framework/Component",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{framework}}.{{component}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "framework",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "component",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "container_id",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tag:YARN_APPLICATION AND hostname:$hostname AND framework:$framework AND component:$component",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Compute Node Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "sys",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "machinecpu_%sys",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "tag:FORWARDER AND hostname:$hostname",
       "timeField": "timestamp"
      },
      {
       "alias": "user",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "machinecpu_%user",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "tag:FORWARDER AND hostname:$hostname",
       "timeField": "timestamp"
      },
      {
       "alias": "iowait",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "machinecpu_%iowait",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "tag:FORWARDER AND hostname:$hostname",
       "timeField": "timestamp"
      },
      {
       "alias": "idle",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "machinecpu_%idle",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "tag:FORWARDER AND hostname:$hostname",
       "timeField": "timestamp"
      },
      {
       "alias": "nice",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "machinecpu_%nice",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "tag:FORWARDER AND hostname:$hostname",
       "timeField": "timestamp"
      },
      {
       "alias": "irq",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "machinecpu_%irq",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "tag:FORWARDER AND hostname:$hostname",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "MEM Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "alias": "available",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "memory_physical",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "tag:FORWARDER AND hostname:$hostname",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "I/O Disks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{disk}}.reads",
       "bucketAggs": [
        {
         "fake": true,
         "field": "disk",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "50" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "9s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "reads",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:OS AND tag:FORWARDER AND hostname:$hostname",
       "timeField": "timestamp"
      },
      {
       "alias": "{{disk}}.writes",
       "bucketAggs": [
        {
         "fake": true,
         "field": "disk",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "50" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "9s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "writes",
         "id": "1",
         "meta": {},
         "pipelineAgg": "select metric",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:OS AND tag:FORWARDER AND hostname:$hostname AND disk:$disk",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Disks bytes reads/writes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "{{disk}}.reads",
       "bucketAggs": [
        {
         "fake": true,
         "field": "disk",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "50" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "9s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "readbytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:OS AND tag:FORWARDER AND hostname:$hostname",
       "timeField": "timestamp"
      },
      {
       "alias": "{{disk}}.writes",
       "bucketAggs": [
        {
         "fake": true,
         "field": "disk",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "50" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "9s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "writebytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:OS AND tag:FORWARDER AND hostname:$hostname AND disk:$disk",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Network tx/rx",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "{{network}}.rx",
       "bucketAggs": [
        {
         "fake": true,
         "field": "network",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "50" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "9s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "rx",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:OS AND tag:FORWARDER AND hostname:$hostname",
       "timeField": "timestamp"
      },
      {
       "alias": "{{network}}.tx",
       "bucketAggs": [
        {
         "fake": true,
         "field": "network",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "50" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "9s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "tx",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:OS AND tag:FORWARDER AND hostname:$hostname AND network:$network",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}