{
 "title": "Garmadon - HDFS",
 "tags": [ "git" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "elasticsearch" },
   {
    "name": "uri",
    "query": "{\"find\": \"terms\", \"field\": \"uri\"}"
   },
   { "name": "path", "query": "/apps,/glup,/tmp,/user,/var" },
   {
    "name": "action",
    "query": "{\"find\": \"terms\", \"field\": \"action\",\"query\":\"uri:$uri AND dst_path:$path\"}"
   }
  ]
 },
 "panels": [
  { "title": "FS OPS Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "FS OPS for $uri:$path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "action",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event_type:FS_EVENT AND uri:$uri AND dst_path:$path",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FS OPS per path  on action $action for $uri",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "apps",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event_type:FS_EVENT AND uri:$uri AND dst_path:\"/apps\" AND action:$action",
     "timeField": "timestamp"
    },
    {
     "alias": "glup",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event_type:FS_EVENT AND uri:$uri AND dst_path:\"/glup\" AND action:$action",
     "timeField": "timestamp"
    },
    {
     "alias": "user",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event_type:FS_EVENT AND uri:$uri AND dst_path:\"/user\" AND action:$action",
     "timeField": "timestamp"
    },
    {
     "alias": "tmp",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event_type:FS_EVENT AND uri:$uri AND dst_path:\"/tmp\" AND action:$action",
     "timeField": "timestamp"
    },
    {
     "alias": "var",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event_type:FS_EVENT AND uri:$uri AND dst_path:\"/var\" AND action:$action",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FS Latency for $uri:$path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{action}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "action",
       "id": "3",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "asc",
        "orderBy": "_term",
        "size": "10"
       },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "method_duration_millis",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "99" ] },
       "type": "percentiles"
      }
     ],
     "query": "event_type:FS_EVENT AND uri:$uri AND dst_path:$path",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FS Latency per path on action $action for $uri",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}} apps",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "method_duration_millis",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "99" ] },
       "type": "percentiles"
      }
     ],
     "query": "event_type:FS_EVENT AND uri:$uri AND dst_path:\"/apps\" AND action:$action",
     "timeField": "timestamp"
    },
    {
     "alias": "{{metric}} glup",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "method_duration_millis",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "99" ] },
       "type": "percentiles"
      }
     ],
     "query": "event_type:FS_EVENT AND uri:$uri AND dst_path:\"/glup\" AND action:$action",
     "timeField": "timestamp"
    },
    {
     "alias": "{{metric}} user",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "method_duration_millis",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "99" ] },
       "type": "percentiles"
      }
     ],
     "query": "event_type:FS_EVENT AND uri:$uri AND dst_path:\"/user\" AND action:$action",
     "timeField": "timestamp"
    },
    {
     "alias": "{{metric}} tmp",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "method_duration_millis",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "99" ] },
       "type": "percentiles"
      }
     ],
     "query": "event_type:FS_EVENT AND uri:$uri AND dst_path:\"/tmp\" AND action:$action",
     "timeField": "timestamp"
    },
    {
     "alias": "{{metric}} var",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "method_duration_millis",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "99" ] },
       "type": "percentiles"
      }
     ],
     "query": "event_type:FS_EVENT AND uri:$uri AND dst_path:\"/var\" AND action:$action",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "event_type:FS_EVENT AND uri:$uri AND dst_path:$path AND action:$action",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "standalone",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type:FS_EVENT AND uri:$uri AND dst_path:$path AND status: FAILURE AND tags: STANDALONE",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FS OPS Per User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "FS OPS $action per user on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "repeat": "action",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "hdfs_user",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per user on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "hdfs_user",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per user on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "hdfs_user",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per user on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "hdfs_user",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per user on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "hdfs_user",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per user on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "hdfs_user",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "FS Latency Per User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "FS Latency $action per user on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "repeat": "action",
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "{{metric}} {{hdfs_user}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "hdfs_user",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "method_duration_millis",
         "id": "1",
         "meta": {},
         "settings": { "percents": [ "99" ] },
         "type": "percentiles"
        }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS Latency $action per user on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "{{metric}} {{hdfs_user}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "hdfs_user",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "method_duration_millis",
         "id": "1",
         "meta": {},
         "settings": { "percents": [ "99" ] },
         "type": "percentiles"
        }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS Latency $action per user on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "{{metric}} {{hdfs_user}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "hdfs_user",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "method_duration_millis",
         "id": "1",
         "meta": {},
         "settings": { "percents": [ "99" ] },
         "type": "percentiles"
        }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS Latency $action per user on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "{{metric}} {{hdfs_user}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "hdfs_user",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "method_duration_millis",
         "id": "1",
         "meta": {},
         "settings": { "percents": [ "99" ] },
         "type": "percentiles"
        }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS Latency $action per user on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "{{metric}} {{hdfs_user}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "hdfs_user",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "method_duration_millis",
         "id": "1",
         "meta": {},
         "settings": { "percents": [ "99" ] },
         "type": "percentiles"
        }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS Latency $action per user on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "{{metric}} {{hdfs_user}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "hdfs_user",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "method_duration_millis",
         "id": "1",
         "meta": {},
         "settings": { "percents": [ "99" ] },
         "type": "percentiles"
        }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "FS OPS Per Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "FS OPS $action per application on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "repeat": "action",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "application_id",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per application on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "application_id",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per application on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "application_id",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per application on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "application_id",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per application on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "application_id",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per application on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "application_id",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "FS OPS Per Framework/Component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "FS OPS $action per application on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "repeat": "action",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{framework}}.{{component}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "framework",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "component",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path AND NOT framework:\"\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per application on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{framework}}.{{component}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "framework",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "component",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path AND NOT framework:\"\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per application on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{framework}}.{{component}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "framework",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "component",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path AND NOT framework:\"\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per application on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{framework}}.{{component}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "framework",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "component",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path AND NOT framework:\"\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per application on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{framework}}.{{component}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "framework",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "component",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path AND NOT framework:\"\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per application on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{framework}}.{{component}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "framework",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "component",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND uri:$uri AND action:$action AND dst_path:$path AND NOT framework:\"\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "FS OPS from StandAlone JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "FS OPS $action per host-user-pid on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "repeat": "action",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{hostname}}-{{hdfs_user}}-{{pid}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "hostname",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "hdfs_user",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND tags:STANDALONE AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per host-user-pid on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{hostname}}-{{hdfs_user}}-{{pid}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "hostname",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "hdfs_user",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND tags:STANDALONE AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per host-user-pid on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{hostname}}-{{hdfs_user}}-{{pid}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "hostname",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "hdfs_user",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND tags:STANDALONE AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per host-user-pid on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{hostname}}-{{hdfs_user}}-{{pid}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "hostname",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "hdfs_user",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND tags:STANDALONE AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per host-user-pid on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{hostname}}-{{hdfs_user}}-{{pid}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "hostname",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "hdfs_user",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND tags:STANDALONE AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS OPS $action per host-user-pid on $uri:$path (top 20)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{hostname}}-{{hdfs_user}}-{{pid}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "hostname",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "hdfs_user",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND tags:STANDALONE AND uri:$uri AND action:$action AND dst_path:$path",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}