{
 "title": "Garmadon - Yarn Application Container",
 "tags": [ "git" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "elasticsearch" },
   {
    "name": "username",
    "query": "{\"find\": \"terms\", \"field\": \"username\", \"query\": \"event_type:APPLICATION_EVENT\", \"size\": 1000}"
   },
   {
    "name": "framework",
    "query": "{\"find\": \"terms\", \"field\": \"framework\",\"query\":\"event_type:APPLICATION_EVENT AND username:$username\"}"
   },
   {
    "name": "application_name",
    "query": "{\"find\": \"terms\", \"field\": \"application_name.keyword\", \"query\": \"event_type:APPLICATION_EVENT AND username:$username AND framework:$framework\"}"
   },
   {
    "name": "application_id",
    "query": "{\"find\": \"terms\", \"field\": \"application_id\", \"query\": \"event_type:APPLICATION_EVENT AND username:$username AND framework:$framework AND application_name:$application_name\", \"size\": 5000}"
   },
   {
    "name": "component",
    "query": "{\"find\": \"terms\", \"field\": \"component\",\"query\":\"application_id:$application_id\"}"
   },
   {
    "name": "container_id",
    "query": "{\"find\": \"terms\", \"field\": \"container_id\", \"query\": \"tags:YARN_APPLICATION AND application_id:$application_id AND component:$component\", \"size\": 5000}"
   },
   {
    "name": "hostname",
    "query": "{\"find\": \"terms\", \"field\": \"hostname\", \"query\": \"application_id:$application_id AND component:$component AND container_id:$container_id\", \"size\": 5000}"
   },
   {
    "name": "uri",
    "query": "{\"find\": \"terms\", \"field\": \"uri\", \"query\": \"application_id:$application_id AND component:$component AND container_id:$container_id\"}"
   }
  ]
 },
 "panels": [
  { "title": "CONTAINER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "content": "Information of container $container_id on server $hostname"
  },
  {
   "title": "Vcore",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "event_type:CONTAINER_MONITORING_EVENT AND type:VCORE AND tags:NODEMANAGER AND application_id:$application_id AND container_id:$container_id",
     "timeField": "timestamp"
    },
    {
     "alias": "requested",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "limit",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "event_type:CONTAINER_MONITORING_EVENT AND type:VCORE AND tags:NODEMANAGER AND application_id:$application_id AND container_id:$container_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event_type:CONTAINER_MONITORING_EVENT AND type:MEMORY AND tags:NODEMANAGER AND application_id:$application_id AND container_id:$container_id",
     "timeField": "timestamp"
    },
    {
     "alias": "limit",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "limit",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "event_type:CONTAINER_MONITORING_EVENT AND type:MEMORY AND tags:NODEMANAGER AND application_id:$application_id AND container_id:$container_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
     "content": "Below graphs are displayed per pid as some jobs are running multiple JVM inside the same container\n\nYou can use the pid variable to display metrics for only one JVM"
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "{{pid}}.%used",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "cpu_%load",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "HEAP Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "alias": "{{pid}}.used",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "heap_used",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      },
      {
       "alias": "max",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "heap_max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "OFF-HEAP Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "alias": "{{pid}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "nonheap_used",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Metadata Space Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "alias": "{{pid}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "metaspace_used",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "GC duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "{{pid}}.ParNew",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "1" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(ParNew)_time",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      },
      {
       "alias": "{{pid}}.G1 Young Generation",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "1" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(G1 Young Generation)_time",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      },
      {
       "alias": "{{pid}}.ConcurrentMarkSweep",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "1" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(ConcurrentMarkSweep)_time",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      },
      {
       "alias": "{{pid}}.G1 Old Generation",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "1" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(G1 Old Generation)_time",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      },
      {
       "alias": "{{pid}}.PS MarkSweep",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "1" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(PS MarkSweep)_time",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      },
      {
       "alias": "{{pid}}.PS Scavenge",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "1" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(PS Scavenge)_time",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "GC Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{pid}}.ConcurrentMarkSweep",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "1" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(ConcurrentMarkSweep)_count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      },
      {
       "alias": "{{pid}}.G1 Old Generation",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "1" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(G1 Old Generation)_count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      },
      {
       "alias": "{{pid}}.G1 Young Generation",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "1" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(G1 Young Generation)_time",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      },
      {
       "alias": "{{pid}}.PS MarkSweep",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "1" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(PS MarkSweep)_count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      },
      {
       "alias": "{{pid}}.PS Scavenge",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "1" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(PS Scavenge)_count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      },
      {
       "alias": "{{pid}}.ParNew",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "1" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "gc(ParNew)_count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "#Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{pid}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "threads_count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "#Threads Created",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{pid}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "threads_total",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "#File Descriptors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{pid}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "descriptors_open",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Advanced",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compile Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{pid}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "compile_count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Compile Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "{{pid}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "compile_time",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Number of compile threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{pid}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "compile_threads",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Safepoint Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{pid}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "safepoints_count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Safepoint Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "{{pid}}.synctime",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "safepoints_synctime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      },
      {
       "alias": "{{pid}}.totaltime",
       "bucketAggs": [
        {
         "fake": true,
         "field": "pid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "safepoints_totaltime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:YARN_APPLICATION AND application_id:$application_id AND container_id:$container_id AND component:$component",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "FS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "FS OPS action per App/Attempt/Container on $uri",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 73 },
     "repeat": "uri",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "action",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND application_id:$application_id AND container_id:$container_id AND uri:$uri AND component:$component",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS Latency action per App/Attempt/Container on $uri",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
     "repeat": "uri",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{metric}} {{action}} (ms)",
       "bucketAggs": [
        {
         "fake": true,
         "field": "action",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "method_duration_millis",
         "id": "1",
         "meta": {},
         "settings": { "percents": [ "99" ] },
         "type": "percentiles"
        }
       ],
       "query": "event_type:FS_EVENT AND application_id:$application_id AND container_id:$container_id AND uri:$uri AND component:$component",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}