{
 "title": "Garmadon - Spark Job",
 "tags": [ "git" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "elasticsearch" },
   {
    "name": "username",
    "query": "{\"find\": \"terms\", \"field\": \"username\",\"query\": \"event_type:SPARK_STAGE_EVENT\", \"size\": 1000}"
   },
   {
    "name": "application_name",
    "query": "{\"find\": \"terms\", \"field\": \"application_name.keyword\", \"query\": \"event_type:SPARK_STAGE_EVENT AND username:$username\", \"size\": 5000}"
   },
   {
    "name": "application_id",
    "query": "{\"find\": \"terms\", \"field\": \"application_id\", \"query\": \"event_type:SPARK_STAGE_EVENT AND application_name.keyword:$application_name AND username:$username\", \"size\": 5000}"
   },
   {
    "name": "attempt_id",
    "query": "{\"find\": \"terms\", \"field\": \"attempt_id\", \"query\": \"event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name\", \"size\": 5000}"
   },
   {
    "name": "uri",
    "query": "{\"find\": \"terms\", \"field\": \"uri\", \"query\": \"application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id\"}"
   },
   {
    "name": "RDD",
    "query": "{\"find\": \"terms\", \"field\": \"rdd_name\", \"query\": \"event_type:SPARK_RDD_STORAGE_STATUS_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id\", \"size\": 1000}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "Container metrics/JVM detailed metrics for this app available here: [Yarn Application Dashboard for $application_id](/dashboard/db/garmadon-yarn-application?orgId=1&var-datasource=$datasource&var-username=All&var-framework=All&var-application_name=All&var-application_id=$application_id&var-component=All&var-container_id=All&var-hostname=All&var-uri=All)"
  },
  { "title": "OVERVIEW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Stages Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "event_type:SPARK_STAGE_STATE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Executors Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "event_type:SPARK_EXECUTOR_STATE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Number of Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "type",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "num_tasks",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type:SPARK_TASK_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Tasks locality",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "locality",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "num_tasks",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type:SPARK_TASK_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "RDD Persistence", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "$RDD",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "repeat": "RDD",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": {
        "interval": "1s",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "memory_used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event_type:SPARK_RDD_STORAGE_STATUS_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id AND rdd_name:$RDD",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": {
        "interval": "1s",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "off_heap_memory_used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event_type:SPARK_RDD_STORAGE_STATUS_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id AND rdd_name:$RDD",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": {
        "interval": "1s",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "disk_used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event_type:SPARK_RDD_STORAGE_STATUS_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id AND rdd_name:$RDD",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "DURATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 37 },
   "content": "Executor run time: Time the executors spends actually running all tasks of the stage (including fetching shuffle data)\n\nJvm gc time: Amount of time the JVM spent in garbage collection while executing the stage \n\nExecutor deserialize time: Time taken on the executors to deserialize all tasks of the stage\n\nResult serialization time: Amount of time spent serializing all tasks of the stage result"
  },
  {
   "title": "Stage runtime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "executor run time",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "executor_run_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    },
    {
     "alias": "jvm gc time",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm_gc_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    },
    {
     "alias": "executor deserialize time",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "executor_deserialize_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    },
    {
     "alias": "result serialization time",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "result_serialization_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    },
    {
     "alias": "blocked fetching shuffle data",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "shuffle_read_fetch_wait_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    },
    {
     "alias": "blocked writting shuffle data",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "shuffle_write_shuffle_time",
       "id": "1",
       "inlineScript": "_value / 1000000",
       "meta": {},
       "settings": { "script": { "inline": "_value / 1000000" } },
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Stage runtime proportions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "executor run time",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "executor_run_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    },
    {
     "alias": "jvm gc time",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm_gc_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    },
    {
     "alias": "executor deserialize time",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "executor_deserialize_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    },
    {
     "alias": "result serialization time",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "result_serialization_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    },
    {
     "alias": "blocked fetching shuffle data",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "shuffle_read_fetch_wait_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    },
    {
     "alias": "blocked writting shuffle data",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "shuffle_write_shuffle_time",
       "id": "1",
       "inlineScript": "_value / 1000000",
       "meta": {},
       "settings": { "script": { "inline": "_value / 1000000" } },
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "SHUFFLE READ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Number of records read from the shuffle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "#shuffle read records",
     "bucketAggs": [
      {
       "fake": true,
       "field": "executor_id",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "shuffle_read_records",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Time the task spent waiting for remote shuffle blocks",
   "type": "graph",
   "description": "This only includes the time blocking on shuffle input data. For instance if block B is being fetched while the task is still not finished processing block A, it is not considered to be blocking on block B.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "shuffle fetch wait time",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "shuffle_read_fetch_wait_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Bytes fetched in the shuffle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "shuffle read local bytes",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "shuffle_read_local_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    },
    {
     "alias": "shuffle read remote bytes",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "shuffle_read_remote_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Number of blocks fetched in this shuffle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "shuffle read local blocks",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "shuffle_read_local_blocks_fetched",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    },
    {
     "alias": "shuffle read remote blocks",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "shuffle_read_remote_blocks_fetched",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "SHUFFLE WRITE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Total number of records written to the shuffle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "shuffle write records",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "shuffle_write_shuffle_records",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Time spent blocking on writes to disk or buffer cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "shuffle write time",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "shuffle_write_shuffle_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Number of bytes written for the shuffle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "shuffle write bytes",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "shuffle_write_shuffle_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "INPUT/OUTPUT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Records",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "#input records",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "input_records",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    },
    {
     "alias": "#output records",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "output_records",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "input bytes",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "input_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    },
    {
     "alias": "output bytes",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "output_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "OTHER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Peak memory used by internal data structures created during shuffles, aggregations and joins",
   "type": "graph",
   "description": "The value of this accumulator should be approximately the sum of the peak sizes across all such data structures created in this task. For SQL jobs, this only tracks all unsafe operators and ExternalSort",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "peak execution memory",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "peak_execution_memory",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "The number of bytes transmitted back to the driver as the TaskResult",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "result size",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "result_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Number of in-memory/on-disk bytes spilled",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "in-memory",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memory_bytes_spilled",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    },
    {
     "alias": "on-disk",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "disk_bytes_spilled",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:SPARK_STAGE_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND attempt_id:$attempt_id",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}