{
 "title": "Garmadon - JVM",
 "tags": [ "git" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "elasticsearch" },
   {
    "name": "tag",
    "query": "{\"find\": \"terms\", \"field\": \"tags\"}"
   },
   {
    "name": "hostname",
    "query": "{\"find\": \"terms\", \"field\": \"hostname\", \"query\": \"tags:$tag\", \"size\": 5000}"
   },
   {
    "name": "username",
    "query": "{\"find\": \"terms\", \"field\": \"username\", \"query\": \"tags:$tag AND hostname:$hostname\", \"size\": 1000}"
   },
   {
    "name": "main_class",
    "query": "{\"find\": \"terms\", \"field\": \"main_class\", \"query\": \"tags:$tag AND hostname:$hostname AND username:$username\", \"size\": 5000}"
   },
   {
    "name": "pid",
    "query": "{\"find\": \"terms\", \"field\": \"pid\", \"query\": \"tags:$tag AND hostname:$hostname AND username:$username AND main_class:$main_class\", \"size\": 5000}"
   },
   {
    "name": "uri",
    "query": "{\"find\": \"terms\", \"field\": \"uri\", \"query\": \"tags:$tag AND hostname:$hostname AND pid:$pid AND main_class:$main_class\"}"
   }
  ]
 },
 "panels": [
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "%usage",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cpu_%load",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "HEAP Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "heap_used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
     "timeField": "timestamp"
    },
    {
     "alias": "max",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "heap_max",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "OFF-HEAP Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "nonheap_used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Metadata Space Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metaspace_used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "ParNew",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "gc(ParNew)_time",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
     "timeField": "timestamp"
    },
    {
     "alias": "G1 Young Generation",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "gc(G1 Young Generation)_time",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
     "timeField": "timestamp"
    },
    {
     "alias": "ConcurrentMarkSweep",
     "bucketAggs": [
      {
       "fake": true,
       "field": "pid",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "1" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "gc(ConcurrentMarkSweep)_time",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
     "timeField": "timestamp"
    },
    {
     "alias": "G1 Old Generation",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "gc(G1 Old Generation)_time",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
     "timeField": "timestamp"
    },
    {
     "alias": "PS MarkSweep",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "gc(PS MarkSweep)_time",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
     "timeField": "timestamp"
    },
    {
     "alias": "PS Scavenge",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "gc(PS Scavenge)_time",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ConcurrentMarkSweep",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "gc(ConcurrentMarkSweep)_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
     "timeField": "timestamp"
    },
    {
     "alias": "G1 Old Generation",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "gc(G1 Old Generation)_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
     "timeField": "timestamp"
    },
    {
     "alias": "G1 Young Generation",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "gc(G1 Young Generation)_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
     "timeField": "timestamp"
    },
    {
     "alias": "PS MarkSweep",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "gc(PS MarkSweep)_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
     "timeField": "timestamp"
    },
    {
     "alias": "PS Scavenge",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "gc(PS Scavenge)_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
     "timeField": "timestamp"
    },
    {
     "alias": "ParNew",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "gc(ParNew)_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "GC Events",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "event_type:GC_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "#Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "#threads",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "threads_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "#Threads Created",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "#threads created",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "threads_total",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "#File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "#file descriptor",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "descriptors_open",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "JVM Advanced",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compile Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "#compile",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "compile_count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Compile Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 42 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Compile duration",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "compile_time",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Number of compile threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "#compile threads",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "compile_threads",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Safepoint Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "#safepoint",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "safepoints_count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Safepoint Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "synctime",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "safepoints_synctime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
       "timeField": "timestamp"
      },
      {
       "alias": "totaltime",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "safepoints_totaltime",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:JVMSTATS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "FS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "FS action on $uri",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
     "repeat": "uri",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "action",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_type:FS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FS Latency action on $uri",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
     "repeat": "uri",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "action",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "method_duration_millis",
         "id": "1",
         "meta": {},
         "settings": { "percents": [ "99" ] },
         "type": "percentiles"
        }
       ],
       "query": "event_type:FS_EVENT AND tags:$tag AND username:$username AND pid:$pid AND hostname:$hostname",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}