{
 "title": "Garmadon - Flink Job Tasks",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "elasticsearch" },
   { "name": "intervals", "query": "10s,30s,1m" },
   {
    "name": "username",
    "query": "{\"find\": \"terms\", \"field\": \"username\",\"query\": \"event_type:FLINK_JOB_MANAGER_EVENT\", \"size\": 1000}"
   },
   {
    "name": "application_name",
    "query": "{\"find\": \"terms\", \"field\": \"application_name.keyword\", \"query\": \"event_type:APPLICATION_EVENT AND username:$username AND framework:\\\"APACHE FLINK\\\"\"}"
   },
   {
    "name": "application_id",
    "query": "{\"find\": \"terms\", \"field\": \"application_id\", \"query\": \"event_type:APPLICATION_EVENT AND username:$username AND framework:\\\"APACHE FLINK\\\" AND application_name:$application_name\", \"size\": 5000}"
   },
   {
    "name": "job_name",
    "query": "{\"find\": \"terms\", \"field\": \"job_name.keyword\", \"query\": \"event_type:FLINK_JOB_EVENT AND username:$username AND application_id:$application_id\", \"size\": 5000}"
   },
   {
    "name": "task_name",
    "query": "{\"find\": \"terms\", \"field\": \"task_name.keyword\", \"query\": \"event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name\", \"size\": 5000}"
   },
   {
    "name": "subtask_index",
    "query": "{\"find\": \"terms\", \"field\": \"subtask_index\", \"query\": \"event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name\", \"size\": 5000}"
   },
   {
    "name": "operator_name",
    "query": "{\"find\": \"terms\", \"field\": \"operator_name.keyword\", \"query\": \"event_type:FLINK_OPERATOR_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index\", \"size\": 5000}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "Set interval to the interval metrics set in flink otherwise it will affect sum result on per_second metrics (Due to the way ES do bucketing aggregation)"
  },
  { "title": "Records/Bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Total number of records this task has read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "in_total",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "num_records_in",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index",
     "timeField": "timestamp"
    },
    {
     "alias": "in_per_second",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "num_records_in_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total number of bytes this task has read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "in_local",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "num_bytes_in_local",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index",
     "timeField": "timestamp"
    },
    {
     "alias": "in_remote",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "num_bytes_in_remote",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index",
     "timeField": "timestamp"
    },
    {
     "alias": "in_local_per_sec",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "num_bytes_in_local_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index",
     "timeField": "timestamp"
    },
    {
     "alias": "in_remote_per_sec",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "num_bytes_in_remote_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total number of records this task has emitted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "out_total",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "num_records_out",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index",
     "timeField": "timestamp"
    },
    {
     "alias": "out_per_second",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "num_records_out_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total number of bytes this task has emitted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "out_total",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "num_bytes_out",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index",
     "timeField": "timestamp"
    },
    {
     "alias": "out_per_second",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "num_bytes_out_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Buffers/Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total number of network buffers this task has emitted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "out_total",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "num_buffers_out",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index",
     "timeField": "timestamp"
    },
    {
     "alias": "out_per_second",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "num_buffers_out_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total number of network buffers this task has read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "in_local_total",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "num_buffers_in_local",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index",
     "timeField": "timestamp"
    },
    {
     "alias": "in_remote_total",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "num_buffers_in_remote",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index",
     "timeField": "timestamp"
    },
    {
     "alias": "in_local_per_second",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "num_buffers_in_local_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index",
     "timeField": "timestamp"
    },
    {
     "alias": "in_remote_per_second",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "num_buffers_in_remote_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "An estimate of the output/input buffers usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "output",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "buffers_out_pool_usage",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index",
     "timeField": "timestamp"
    },
    {
     "alias": "input",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "buffers_in_pool_usage",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "The number of queued output/input buffers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "output",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "buffers_output_queue_length",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index",
     "timeField": "timestamp"
    },
    {
     "alias": "input",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "buffers_input_queue_length",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_TASK_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Operator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Last watermark emitted/received by operator",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 50 },
       "type": "raw_document"
      }
     ],
     "query": "event_type:FLINK_OPERATOR_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index AND operator_name.keyword:$operator_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Kafka Commits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "succeeded",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "commits_succeeded",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_OPERATOR_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index AND operator_name.keyword:$operator_name",
     "timeField": "timestamp"
    },
    {
     "alias": "failed",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "commits_failed",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event_type:FLINK_OPERATOR_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index AND operator_name.keyword:$operator_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Kafka Committed Offsets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{topic.keyword}}.{{partition.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "topic.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "partition.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "committed_offsets",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "event_type:FLINK_KAFKA_CONSUMER_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index AND operator_name.keyword:$operator_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Others",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "num_late_records_dropped",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "num_late_records_dropped",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event_type:FLINK_OPERATOR_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index AND operator_name.keyword:$operator_name",
     "timeField": "timestamp"
    },
    {
     "alias": "num_splits_processed",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "num_splits_processed",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event_type:FLINK_OPERATOR_EVENT AND application_id:$application_id AND job_name.keyword:$job_name AND task_name.keyword:$task_name AND subtask_index:$subtask_index AND operator_name.keyword:$operator_name",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}