{
 "title": "Garmadon - Flink Job",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "elasticsearch" },
   { "name": "intervals", "query": "10s,30s,1m" },
   {
    "name": "username",
    "query": "{\"find\": \"terms\", \"field\": \"username\",\"query\": \"event_type:FLINK_JOB_MANAGER_EVENT\", \"size\": 1000}"
   },
   {
    "name": "application_name",
    "query": "{\"find\": \"terms\", \"field\": \"application_name.keyword\", \"query\": \"event_type:APPLICATION_EVENT AND username:$username AND framework:\\\"APACHE FLINK\\\"\"}"
   },
   {
    "name": "application_id",
    "query": "{\"find\": \"terms\", \"field\": \"application_id\", \"query\": \"event_type:APPLICATION_EVENT AND username:$username AND framework:\\\"APACHE FLINK\\\" AND application_name.keyword:$application_name\", \"size\": 5000}"
   },
   {
    "name": "job_name",
    "query": "{\"find\": \"terms\", \"field\": \"job_name.keyword\", \"query\": \"event_type:FLINK_JOB_EVENT AND application_id:$application_id AND application_name.keyword:$application_name\", \"size\": 5000}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "Container/JVM detailed metrics for this app available here: [Yarn Application Dashboard for $application_id](dashboard/db/garmadon-yarn-application?orgId=1&var-datasource=$datasource&var-username=All&var-framework=All&var-application_id=$application_id&var-component=All&var-container_id=All&var-hostname=All&var-uri=All)"
  },
  {
   "title": "JobManager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Numer Of TaskManager",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "num_registered_task_managers",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:FLINK_JOB_MANAGER_EVENT AND application_id:$application_id AND application_name.keyword:$application_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Numer Of Running Jobs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "num_running_jobs",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:FLINK_JOB_MANAGER_EVENT AND application_id:$application_id AND application_name.keyword:$application_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Numer Of Task Slots",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "task_slots_available",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "task_slots_available",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:FLINK_JOB_MANAGER_EVENT AND application_id:$application_id AND application_name.keyword:$application_name",
       "timeField": "timestamp"
      },
      {
       "alias": "task_slots_total",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "task_slots_total",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:FLINK_JOB_MANAGER_EVENT AND application_id:$application_id AND application_name.keyword:$application_name",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Job Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{job_name.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "job_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "uptime",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event_type:FLINK_JOB_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND job_name.keyword:$job_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{job_name.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "job_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "downtime",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event_type:FLINK_JOB_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND job_name.keyword:$job_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Number of restarts and time it took to restart the job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{job_name.keyword}} restartingTime",
     "bucketAggs": [
      {
       "fake": true,
       "field": "job_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "restarting_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event_type:FLINK_JOB_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND job_name.keyword:$job_name",
     "timeField": "timestamp"
    },
    {
     "alias": "{{job_name.keyword}} fullRestarts",
     "bucketAggs": [
      {
       "fake": true,
       "field": "job_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "full_restarts",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event_type:FLINK_JOB_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND job_name.keyword:$job_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Checkpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number Of Checkpoints",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{job_name.keyword}} in progress",
       "bucketAggs": [
        {
         "fake": true,
         "field": "job_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "number_of_in_progress_checkpoints",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:FLINK_JOB_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND job_name.keyword:$job_name",
       "timeField": "timestamp"
      },
      {
       "alias": "{{job_name.keyword}} failed",
       "bucketAggs": [
        {
         "fake": true,
         "field": "job_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "number_of_failed_checkpoints",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:FLINK_JOB_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND job_name.keyword:$job_name",
       "timeField": "timestamp"
      },
      {
       "alias": "{{job_name.keyword}} completed",
       "bucketAggs": [
        {
         "fake": true,
         "field": "job_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "number_of_completed_checkpoints",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:FLINK_JOB_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND job_name.keyword:$job_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "{{job_name.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "job_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "last_checkpoint_duration",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:FLINK_JOB_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND job_name.keyword:$job_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Size",
     "type": "graph",
     "description": "The number of buffered bytes during alignment over all subtasks for the last checkpoint",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "{{job_name.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "job_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "last_checkpoint_size",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:FLINK_JOB_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND job_name.keyword:$job_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Alignement Buffered",
     "type": "graph",
     "description": "The number of buffered bytes during alignment over all subtasks for the last checkpoint",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "{{job_name.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "job_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "last_checkpoint_alignment_buffered",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:FLINK_JOB_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND job_name.keyword:$job_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Restore time for $job_name",
     "type": "table",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 47 },
     "repeat": "job_name",
     "targets": [
      {
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": { "size": 1 },
         "type": "raw_document"
        }
       ],
       "query": "event_type:FLINK_JOB_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND job_name.keyword:$job_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Restore time for $job_name",
     "type": "table",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 47 },
     "targets": [
      {
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": { "size": 1 },
         "type": "raw_document"
        }
       ],
       "query": "event_type:FLINK_JOB_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND job_name.keyword:$job_name",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Consumer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka lag",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{job_name.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "job_name.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "records_lag_max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "event_type:FLINK_OPERATOR_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND job_name.keyword:$job_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Kafka records rate consumption",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{job_name.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "job_name.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "records_consumed_rate",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:FLINK_OPERATOR_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND job_name.keyword:$job_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Kafka bytes rate consumption",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "{{job_name.keyword}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "job_name.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "$intervals", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "bytes_consumed_rate",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:FLINK_OPERATOR_EVENT AND application_id:$application_id AND application_name.keyword:$application_name AND job_name.keyword:$job_name",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "TaskManager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Memory Segments",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{container_id}} available",
       "bucketAggs": [
        {
         "fake": true,
         "field": "container_id",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "network_available_memory_segments",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:FLINK_TASK_MANAGER_EVENT AND application_id:$application_id AND application_name.keyword:$application_name",
       "timeField": "timestamp"
      },
      {
       "alias": "{{container_id}} used",
       "bucketAggs": [
        {
         "fake": true,
         "field": "container_id",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "network_total_memory_segments",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "event_type:FLINK_TASK_MANAGER_EVENT AND application_id:$application_id AND application_name.keyword:$application_name",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}